//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub mod prelude;

pub mod channel;
pub mod instrument;
pub mod language;
pub mod registration;
pub mod role;
pub mod style;
pub mod team;
pub mod user;
