//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub mod prelude;

pub mod instrument;
pub mod instrument_local;
pub mod language;
pub mod language_local;
pub mod registration;
pub mod user;
