//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::channel::Entity as Channel;
pub use super::instrument::Entity as Instrument;
pub use super::language::Entity as Language;
pub use super::registration::Entity as Registration;
pub use super::role::Entity as Role;
pub use super::style::Entity as Style;
pub use super::team::Entity as Team;
pub use super::user::Entity as User;
